dist: trusty
sudo: false
language: php
php:
  - 7.2.0

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - cp .env.travis .env
  - mysql -u root -e 'create database `urlhum-test`;'
  - mysql -u root -e "CREATE USER 'urlhum-test'@'localhost' IDENTIFIED BY 'secret';"
  - mysql -u root -e "GRANT ALL ON \`urlhum-test\`.* TO 'urlhum-test'@'localhost';"
  - mysql -u root -e "FLUSH PRIVILEGES;"
  - composer install --prefer-dist --no-interaction
  - php artisan key:generate
  - php artisan clear-compiled -n
  - php artisan migrate --force -n --database=testing
  - php artisan db:seed --force -n --database=testing
  - php artisan settings:set

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - cat storage/logs/laravel.log

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml